#!/bin/bash
set -e

echo "Enter the name of the hex:"
read NAME

echo "Enter the hex architecture [armv7l or x86_64|:"
read ARCH

RANGE=`echo 10.$(shuf -i 0-255 -n 1).$(shuf -i 0-255 -n 1)`
echo "Enter the network range or press enter to use $RANGE:"
read RANGE_ATTEMPT
[ "${RANGE_ATTEMPT}" != "" ] && RANGE="${RANGE_ATTEMPT}"

touch profiles/$NAME
echo "NAME=$NAME" >> profiles/$NAME
echo "ARCH=$ARCH" >> profiles/$NAME
echo "RANGE=$RANGE" >> profiles/$NAME

echo "Profile $NAME has been added to the list of profiles."