#!/bin/bash
set -e

echo "Enter the name of the hex:"
read NAME

echo "Enter the hex architecture [armv7l or x86_64|:"
read ARCH

echo "Enter the hex sequence id:"
read SEQ

RANGE="172.17.$SEQ"
MASK="255.255.255.0"

touch profiles/$NAME
echo "SEQ=$SEQ" >> profiles/$NAME
echo "NAME=$NAME" >> profiles/$NAME
echo "ARCH=$ARCH" >> profiles/$NAME
echo "RANGE=$RANGE" >> profiles/$NAME
echo "MASK=$MASK" >> profiles/$NAME

echo "Generating the ssh keys"
mkdir ./keys/${NAME}
ssh-keygen -N "" -f ./keys/${NAME}/id_rsa

echo "Profile $NAME has been added to the list of profiles."
