---
# This playbook deploys the AWX application (database, web and worker) to a
# single server.

- hosts: all
  roles:
    - { role: unmount }
    - { role: partition }
    - { role: mount }
    - { role: common }
    - { role: master, when: "node.type == 'master'" }
    - { role: slave, when: "node.type == 'slave'"  }
    - { role: unmount }

