---
- include: prepare.yml

# -- Unmount existing partitions, recreate the partition table, install the bootloader and mount the new partitions again
- include: unmount.yml
- include: partition.yml
- include: mount.yml


# -- create the root filesystem and install the kernel
- include: node-fs.yml
- include: node-kernel.yml

# -- configure the bootloader
- include: node-bootloader.yml

# -- configure the serial port
- include: node-serial.yml

# -- configure the network
- include: node-network-general.yml
- include: node-network-{{node.type}}.yml

# -- configure the security
- include: node-security.yml

# -- create the users
- include: node-users.yml

# -- add the node disk
- include: node-disk.yml

# -- add the bigboards configuration
- include: node-bigboards.yml

# -- Unmount the SD-Card
- include: unmount.yml