- name: Copy the UDev Rules
  copy: src=70-persistent-net.rules dest=/media/rootfs/etc/udev/rules.d/70-persistent-net.rules owner=root group=root
  tags: 
    - config

- name: Copy hostname configuration
  template: src=hostname.j2 dest=/media/rootfs/etc/hostname owner=root group=root
  tags: 
    - config

- name: Copy DNS configuration
  template: src=resolv.conf.j2 dest=/media/rootfs/etc/resolv.conf owner=root group=root
  tags: 
    - config

- name: Copy hosts file
  template: src=hosts.j2 dest=/media/rootfs/etc/hosts owner=root group=root
  tags: 
    - config

- name: Disable IPv6
  lineinfile: dest=/media/rootfs/etc/sysctl.conf regexp='^{{item}}' line='{{item}}=1'
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  tags:
    - kernel

- name: Change the number of open files per user
  lineinfile: dest=/media/rootfs/etc/security/limits.conf regexp='^\* soft nofile' line='* soft nofile 65536'
  tags:
    - kernel

- name: Change the number of open files per user
  lineinfile: dest=/media/rootfs/etc/security/limits.conf regexp='^\* hard nofile' line='* hard nofile 65536'
  notify: Update nofile
  tags:
    - kernel

- name: Change the number of open files per user
  lineinfile: dest=/media/rootfs/etc/security/limits.conf regexp='^\* soft nofile' line='* soft nofile 65536'
  notify: Update nofile
  tags:
    - kernel

- name: Change the number of open files per user
  lineinfile: dest=/media/rootfs/etc/pam.d/common-session regexp='^session required pam_limits' line='session required pam_limits.so'
  tags:
    - kernel