- name: Copy network configuration
  template: src=interfaces-{{node.type}}.j2 dest=/media/rootfs/etc/network/interfaces owner=root group=root
  tags: 
    - config

- name: Enable Ipv4 forwarding
  lineinfile: dest=/media/rootfs/etc/sysctl.conf regexp='^net.ipv4.ip_forward=' line='net.ipv4.ip_forward=1'
  tags:
    - config

- name: Copy the iptables script
  template: src=iptables.j2 dest=/media/rootfs/etc/iptables.up.rules
  tags:
    - config

- name: Configure IPTables when the interface becomes available
  file: src=etc/network/if-pre-up.d/iptables dest=/media/rootfs/etc/iptables.up.rules
  tags:
    - config