- name: Copy the kernel
  copy: src={{kernel.version}}.zImage dest=/media/boot/zImage

- name: Create the DTBS directory
  file: state=directory path=/media/boot/dtbs

- name: Extract the DTBS
  shell: tar xvf /tmp/{{kernel.version}}-dtbs.tar.gz -C /media/boot/dtbs/

- name: Extract the modules
  shell: tar xvf /tmp/{{kernel.version}}-modules.tar.gz -C /media/rootfs