- name: Remove the current partition table
  shell: dd if=/dev/zero of={{disk}} bs=512 count=1 conv=notrunc
  tags:
    - disk

- name: Partition the disk 
  shell: sfdisk --force {{disk}} < /tmp/partitioning.cfg
  tags:
    - disk

- name: Create the filesystem for the boot partition
  shell: mkfs.ext2 -L boot {{disk}}1
  tags:
    - disk

- name: Create the filesystem for the root partition
  shell: mkfs.ext4 -L rootfs {{disk}}2
  tags:
    - disk

- name: Install the bootloader
  shell: dd if=/tmp/u-boot.imx of={{disk}} bs=512 seek=2
  tags:
    - disk