---
- name: install ubuntu awx apt repository
  template: src=awx_repo.j2 dest=/etc/apt/sources.list.d/awx_repo.list

- name: install python-pip package for ubuntu 12.04
  apt: name=python-pip
  when: ansible_lsb.codename == "precise"

- name: install django 1.5.4 via pip for ubuntu 12.04
  pip: name=django version=1.5.4
  when: ansible_lsb.codename == "precise"

- name: install django via apt for ubuntu 12.10 or later
  apt: name=python-django
  when: ansible_lsb.codename != "precise"

- name: install required packages via apt
  apt: name={{ item }}
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - postgresql
    - python-psycopg2
    - python-setuptools
    - python-ldap
    - supervisor
    - git 
    - subversion
    - mercurial

- name: install awx package via apt
  apt: name=awx update_cache=yes force=yes state=latest

