#!/bin/bash


# Hosted Zone ID e.g. BJBK35SKMM9OE
ZONEID="Z1RUAV64525T6D"


function update_ip() {
    HEX_NAME=$1
    NODE_SEQ=$2
    IP=$3

    TMPFILE=$(mktemp /tmp/temporary-file.XXXXXXXX)

    cat > ${TMPFILE} << EOF
    {
      "Comment":"Dynamic update ${HEX_NAME} TO ${IP}",
      "Changes":[
      {
          "Action":"UPSERT",
          "ResourceRecordSet":{
            "ResourceRecords":[
              {
                "Value":"$IP"
              }
            ],
            "Name":"node-${NODE_SEQ}.${HEX_NAME}.hex.bigboards.io",
            "Type":"A",
            "TTL":300
          }
        }
EOF

    if [ "$NODE_SEQ" -eq "1" ]; then
        cat >> ${TMPFILE} << EOF
        ,{
          "Action":"UPSERT",
          "ResourceRecordSet":{
            "ResourceRecords":[
              {
                "Value":"node-${NODE_SEQ}.${HEX_NAME}.hex.bigboards.io"
              }
            ],
            "Name":"${HEX_NAME}.hex.bigboards.io",
            "Type":"CNAME",
            "TTL":300
          }
        }
EOF
    fi

cat >> ${TMPFILE} << EOF
      ]
    }
EOF

    export AWS_ACCESS_KEY_ID=AKIAIPPRDWFZYLAB7Y2A
    export AWS_SECRET_ACCESS_KEY=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

    # Update the Hosted Zone record
    aws route53 change-resource-record-sets \
        --hosted-zone-id $ZONEID \
        --change-batch file://"$TMPFILE"
}

# update_ip hex_name node_seq ip
IFCFG="ifconfig eth1"
IP=$($IFCFG | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
NODE_SEQ=$(echo `ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'` | rev | cut -d '.' -f 1)
HEX_NAME=$(hostname |cut -d '-' -f 1)

update_ip $HEX_NAME $NODE_SEQ $IP
