- name: be sure the rootfs is empty
  shell: rm -rf /media/bbfs/*

- name: be sure the rootfs image is copied to the local filesystem
  get_url: url={{arm.rootfs}} dest={{cacheDir}}/rootfs-arm.tgz

- name: be sure the rootfs is unpacked onto the right location
  unarchive: copy=yes src={{cacheDir}}/rootfs-arm.tgz dest=/media/bbfs