#- name: install python using CLI to allow ansible to work
#  command: apt-get install -y python

- name: create the .ssh directory
  file:
    state: directory
    path: '/media/bbfs/home/bb/.ssh'
    owner: bb

- name: copy the ssh keys to the right directory
  copy:
    src: '../keys/{{hex.name}}/{{item}}'
    dest: '/media/bbfs/home/bb/.ssh/{{item}}'
    owner: bb
  with_items:
    - 'id_rsa'
    - 'id_rsa.pub'

- name: allow the bb user to login without a password
  copy:
    src: '../keys/{{hex.name}}/id_rsa.pub'
    dest: '/media/bbfs/home/bb/.ssh/authorized_keys'
    owner: bb
    mode: 600

- name: install the software packages
  apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: "yes"
  with_items:
    - python-pip
    - nodejs
    - nodejs-legacy
    - npm
    - node-colors
    - vim

- name: install the aws tools
  pip:
    name: 'awscli'

- name: set the new bash prompt
  lineinfile: dest=/etc/bash.bashrc regexp='^PS1=' line="PS1=$'\u2b22 {{ hex.name }} \u@\h \w\$ '"

#    - name: chroot - copy the resolv.conf so we have networking
#      copy: src=/etc/resolv.conf dest=/media/bbfs/etc/resolv.conf

#    - name: chroot - bind mount all the filesystems we need
#      shell: for f in /sys /proc /dev ; do mount --rbind $f /media/bbfs$f ; done

- name: configure the network
  template: src=templates/{{item}} dest=/{{item}} owner=root group=root
  with_items:
    - "etc/hostname"
    - "etc/network/interfaces"
    - "etc/dhcp/dhclient.conf"
    - "etc/hosts"
    - "etc/avahi/avahi-daemon.conf"

- name: make sure the nodes will register themselves with amazon dns
  template: src=templates/etc/network/if-up.d/dns dest=/etc/network/if-up.d/dns owner=root group=root mode=755

#- name: add the bb user to the sudoers
#  lineinfile: dest=/etc/sudoers state=present regexp='^bb ALL\=' line='bb ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'