#- name: install python using CLI to allow ansible to work
#  command: apt-get install -y python

#- name: install the software packages
#  apt:
#    name: "{{ item }}"
#    state: "latest"
#    update_cache: "yes"
#  with_items:
#    - linux-headers-generic
#    - linux-image-generic
#    - rsyslog
#    - avahi-daemon
#    - avahi-utils
#    - python

- name: set the new bash prompt
  lineinfile: dest=/etc/bash.bashrc regexp='^PS1=' line="PS1=$'\u2b22 {{ hex.name }} \u@\h \w\$ '"

#    - name: chroot - copy the resolv.conf so we have networking
#      copy: src=/etc/resolv.conf dest=/media/bbfs/etc/resolv.conf

#    - name: chroot - bind mount all the filesystems we need
#      shell: for f in /sys /proc /dev ; do mount --rbind $f /media/bbfs$f ; done

- name: configure the network
  template: src=templates/{{item}} dest=/{{item}} owner=root group=root
  with_items:
    - "etc/hostname"
    - "etc/network/interfaces"
    - "etc/dhcp/dhclient.conf"
    - "etc/hosts"
    - "etc/avahi/avahi-daemon.conf"

#- name: add the bb user to the sudoers
#  lineinfile: dest=/etc/sudoers state=present regexp='^bb ALL\=' line='bb ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'