---
- name: be sure the host system has the right network configuration
  template: src=host/{{item}} dest=/media/bbfs/{{item}} owner=root group=root
  with_items:
    - etc/hostname
    - etc/hosts
    - etc/network/interfaces
    - etc/dhcp/dhclient.conf
    - etc/avahi/avahi-daemon.conf

- name: be sure avahi is started at boot
  service: name=avahi-daemon enabled=true