---
- name: be sure all partitions are removed
  shell: parted -s {{disk.dev}} mklabel msdos
  tags:
    - disk

- name: be sure the disk is holding the correct partition layout 
  shell: parted {{disk.dev}} mkpart primary 0% 100%
  tags:
    - disk

- name: be sure the disks have the right partition format
  shell: mkfs.ext4 {{disk.part}}
  tags:
    - disk