---
- name: be sure the rootfs is empty
  shell: rm -rf /media/bbfs/*

- name: be sure the rootfs image is copied to the local filesystem
  get_url: url={{intel.rootfs}} dest={{cacheDir}}/rootfs-intel.tgz

- name: be sure the rootfs is unpacked onto the right location
  shell: tar -xzf {{cacheDir}}/rootfs-intel.tgz -C /media/bbfs
#  unarchive: copy=yes src={{cacheDir}}/rootfs-intel.tgz dest=/media/bbfs

- name: be sure the grub configuration has been corrected
  copy: src='grub.cfg' dest='/media/bbfs/boot/grub/grub.cfg'

- name: be sure the bootloader is installed
  shell: grub-install --boot-directory /media/bbfs/boot --target i386-pc {{disk.dev}}

- name: be sure the new bash prompt is active
  lineinfile: dest=/media/bbfs/etc/bash.bashrc regexp='^PS1=' line="PS1=$'\u2b22 {{ hex.name }} \u@\h \w\$ '"

- name: be sure the udev network rules are dropped
  copy: src=70-persistent-net.rules dest=/media/bbfs/etc/udev/rules.d/70-persistent-net.rules

- name: be sure the correct sources.list file is available
  copy: src=sources.list-{{hex.arch}} dest=/media/bbfs/etc/apt

- name: be sure the log files have the correct permissions
  file: state=touch path=/media/bbfs/{{item}} owner=101 group=4
  with_items:
    - var/log/syslog
    - var/log/auth.log
    - var/log/kern.log

- name: be sure multicast_snooping is disabled when starting avahi
  copy: src=avahi-daemon.conf dest=/media/bbfs/etc/init/avahi-daemon.conf