---
- name: be sure the new bash prompt is active
  lineinfile: dest=/media/bbfs/etc/bash.bashrc regexp='^PS1=' line="PS1=$'\u2b22 {{ hex.name }} \u@\h \w\$ '"

- name: be sure the correct sources.list file is available
  copy: src=sources.list dest=/media/bbfs/etc/apt

- name: be sure the log files have the correct permissions
  file: state=present path=/media/bbfs/{{item}} owner=101 group=4
  with_items:
    - var/log/syslog
    - var/log/auth.log
    - var/log/kern.log
