---

- name: be sure the mountpoints exist
  file: state=directory path=/media/{{item.key}}
  with_dict: disk.partitions
  tags:
    - disk

- name: be sure the partitions are mounted
  shell: mount -t {{item.value.type}} {{item.value.dev}} /media/{{item.key}}
  with_dict: disk.partitions
  tags: 
    - disk