---
- name: be sure the mountpoints exist
  file: state=directory path=/media/bbfs
  with_dict: disk.partitions
  tags:
    - disk

- name: be sure the partitions are mounted
  shell: mount -t ext4 {{disk.part}} /media/bbfs
  tags: 
    - disk