#- name: install python using CLI to allow ansible to work
#  command: apt-get install -y python

- name: change the user name
  shell: usermod -l bb ubuntu

- name: change the user home directory
  shell: usermod -m -d /home/bb bb

- name: create the .ssh directory
  file:
    state: directory
    path: '/home/bb/.ssh'
    owner: bb

- name: copy the ssh keys to the right directory
  copy:
    src: '../keys/{{hex.name}}/{{item}}'
    dest: '/home/bb/.ssh/{{item}}'
    owner: bb
  with_items:
    - 'id_rsa'
    - 'id_rsa.pub'

- name: allow the bb user to login without a password
  copy:
    src: '../keys/{{hex.name}}/id_rsa.pub'
    dest: '/home/bb/.ssh/authorized_keys'
    owner: bb
    mode: 600

- name: install the software packages
  apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: "yes"
  with_items:
    - curl
    - ntp
    - nodejs
    - nodejs-legacy
    - npm
    - node-colors
    - vim

- name: make sure we have a correct date
  ignore_errors: yes
  shell: ntpdate -s time.nist.gov

- name: install pip
  shell: curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python2.7

- name: install the aws tools
  pip:
    name: 'awscli'

- name: set the new bash prompt
  lineinfile: dest=/etc/bash.bashrc regexp='^PS1=' line="PS1=$'\u2b22 {{ hex.name }} \u@\h \w\$ '"

- name: configure the network
  template: src=templates/{{item}} dest=/{{item}} owner=root group=root
  with_items:
    - "etc/hostname"
    - "etc/network/interfaces"
    - "etc/dhcp/dhclient.conf"
    - "etc/hosts"

- name: make sure the nodes will register themselves with amazon dns
  template: src=templates/etc/network/if-up.d/dns dest=/etc/network/if-up.d/dns owner=root group=root mode=755

- name: add the bb user to the sudoers
  lineinfile: dest=/etc/sudoers state=present regexp='^bb ALL\=' line='bb ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'