---
- name: be sure all data was synced
  shell: "sync && sync"

- name: be sure the partitions are not mounted
  shell: umount -t {{item.value.type}} {{item.value.dev}}
  ignore_errors: yes
  with_dict: disk.partitions
  tags: 
    - disk