---

# -- ----------------------------------------------------------------------- --
# -- Ansible local facts
# -- ----------------------------------------------------------------------- --
- name: be sure the bb home directory exists
  file: state=directory path=/media/bbfs/opt/bb owner=1000 group=999

- name: be sure the ansible local facts directory exists
  file: state=directory path=/media/bbfs/etc/ansible/facts.d

- name: be sure the hex facts are deployed to the ansible local facts directory
  template: src=bb.fact dest=/media/bbfs/etc/ansible/facts.d/bb.fact

- name: be sure the hosts of this hex are copied to the bb directory
  template: src=hosts dest=/media/bbfs/opt/bb/hosts
