---

# -- ----------------------------------------------------------------------- --
# -- Ansible local facts
# -- ----------------------------------------------------------------------- --
- name: be sure the ansible local facts directory exists
  file: state=directory path=/media/bbfs/etc/ansible/facts.d

- name: be sure the hex facts are deployed to the ansible local facts directory
  template: src=hex.fact dest=/media/bbfs/etc/ansible/facts.d/hex.fact
