---

# -- ----------------------------------------------------------------------- --
# -- The Boot Filesystem
# -- ----------------------------------------------------------------------- --
- name: be sure the UBoot configuration has been set
  template: src=uEnv.txt.j2 dest=/media/boot/uEnv.txt
  tags:
    - rootfs
    - boot

# -- ----------------------------------------------------------------------- --
# -- The Root Filesystem
# -- ----------------------------------------------------------------------- --

- name: be sure the rootfs is empty
  shell: rm -rf /media/root/*
  tags:
    - rootfs

- name: be sure the rootfs image is copied to the local filesystem
  get_url: url={{mirror}}/images/{{version.rootfs}} dest={{cacheDir}}/{{version.rootfs}}
  tags:
    - rootfs

- name: be sure the rootfs is unpacked onto the right location
  unarchive: copy=yes src={{cacheDir}}/{{version.rootfs}} dest=/media/root
  tags:
    - rootfs

# -- ----------------------------------------------------------------------- --
# -- Patch the Root Filesystem
# -- ----------------------------------------------------------------------- --
- name: be sure the udev rules for network devices have been reset
  copy: src=70-persistent-net.rules dest=/media/root/etc/udev/rules.d/70-persistent-net.rules owner=root group=root
  tags: 
    - rootfs

# -- ----------------------------------------------------------------------- --
# -- Patch the network configuration
# -- ----------------------------------------------------------------------- --

- name: be sure the system has the right hostname
  template: src=hostname.j2 dest=/media/root/etc/hostname owner=root group=root
  tags: 
    - rootfs
    - network

- name: be sure the system is using the correct DNS servers
  template: src=resolv.conf.j2 dest=/media/root/etc/resolv.conf owner=root group=root
  tags: 
    - rootfs
    - network

- name: be sure the system knows the other nodes inside the hex
  template: src=hosts.j2 dest=/media/root/etc/hosts owner=root group=root
  tags: 
    - rootfs
    - network

# -- ----------------------------------------------------------------------- --
# -- Patch the repsository configuration
# -- ----------------------------------------------------------------------- --

- name: be sure the system uses the right apt repositories
  copy: src=etc/apt/sources.list dest=/media/root/etc/apt/sources.list owner=root group=root
  tags:
    - rootfs
    - apt

# -- ----------------------------------------------------------------------- --
# -- Copy the keys used for authenticating
# -- ----------------------------------------------------------------------- --

- name: be sure the bigboards user has a .ssh directory
  file: path=/media/root/opt/bb/.ssh state=directory mode=0700 owner=1000 group=1002
  tags:
    - rootfs
    - users

- name: be sure the ssh key for the bigboards user has been copied
  copy: src=keys/ dest=/media/root/opt/bb/.ssh/ mode=0600 owner=1000 group=1002
  tags:
    - rootfs
    - users

- name: be sure the bigboards key is authorized to login
  copy: src=keys/id_rsa.pub dest=/media/root/opt/bb/.ssh/authorized_keys mode=0600 owner=1000 group=1002
  tags:
    - rootfs
    - users


# -- ----------------------------------------------------------------------- --
# -- The Kernel
# -- ----------------------------------------------------------------------- --
- name: be sure the kernel files are copied to the local filesystem
  get_url: url={{mirror}}/kernel/{{item}} dest={{cacheDir}}
  with_items:
    - '{{version.kernel}}-modules.tar.gz'
    - '{{version.kernel}}.zImage'
    - imx6q-wandboard.dtb
  tags:
    - rootfs
    - kernel

- name: be sure the kernel is availble on the boot disk
  copy: src={{cacheDir}}/{{version.kernel}}.zImage dest=/media/boot/zImage
  tags:
    - rootfs
    - kernel

- name: be sure the device tree is availble on the boot disk
  copy: src={{cacheDir}}/imx6q-wandboard.dtb dest=/media/boot/imx6q-wandboard.dtb
  tags:
    - rootfs
    - kernel

- name: be sure the kernel modules are available
  shell: tar xvf {{cacheDir}}/{{version.kernel}}-modules.tar.gz -C /media/root
  tags:
    - rootfs
    - kernel

# -- ----------------------------------------------------------------------- --
# -- Ansible local facts
# -- ----------------------------------------------------------------------- --
- name: be sure the ansible local facts directory exists
  file: state=directory path=/media/root/etc/ansible/facts.d

- name: be sure the hex facts are deployed to the ansible local facts directory
  template: src=hex.fact dest=/media/root/etc/ansible/facts.d/hex.fact
