- name: Create the bigboards group
  lineinfile: dest=/media/rootfs/etc/group regexp='^bigboards' line='bigboards:x:3333:' owner=root group=root mode=0644
  tags:
    - users

- name: Create the bigboards user home directory
  file: path=/media/rootfs/opt/bigboards state=directory
  tags:
    - users

- name: Create the bigboards user passwd entry
  lineinfile: dest=/media/rootfs/etc/passwd regexp='^bb-user' line='bb-user:x:3333:3333:BigBoards User:/opt/bigboards:/bin/bash' owner=root group=root mode=0644
  tags:
    - users

- name: Create the bigboards user shadow entry
  lineinfile: dest=/media/rootfs/etc/shadow regexp='^bb-user' line='bb-user:$6$oCgCUpM6$bkImWjguz6Wnm9tjUB5aY1Ke92mmOcN2/smdsPnsJG7kA/Lcp/YZ0oZLgfUfG7F7r3HqWEYQq5AIZ71TE7JdO/:13064:0:99999::::' owner=root group=root mode=0644
  tags:
    - users

- name: Create the bigboards .ssh directory
  file: path=/media/rootfs/opt/bigboards/.ssh state=directory mode=0644 owner=3333
  tags:
    - users

- name: Copy the ssh keys for the bigboards user
  copy: src=keys/ dest=/media/rootfs/opt/bigboards/.ssh/ mode=0644 owner=3333 group=3333
  tags:
    - users

- name: Copy the authorized ssh keys for the bigboards user
  copy: src=keys/id_rsa.pub dest=/media/rootfs/opt/bigboards/.ssh/authorized_keys mode=0644 owner=3333 group=3333
  tags:
    - users
