---

# -- ----------------------------------------------------------------------- --
# -- WIFI
# -- ----------------------------------------------------------------------- --
- name: be sure the wifi nvram file is available
  get_url: url=https://raw.github.com/Freescale/meta-fsl-arm-extra/master/recipes-bsp/broadcom-nvram-config/files/wandboard/nvram.txt dest=/media/root/lib/firmware/brcm/brcmfmac-sdio.txt validate_certs=no
  tags:
    - network

- name: be sure the link to the firmware for the broadcom wifi adapter is available
  file: state=link force=yes src=/lib/firmware/brcm/brcmfmac4329.bin dest=/media/root/lib/firmware/brcm/brcmfmac-sdio.bin
  tags:
    - network

- name: be sure the node communicates to the outside world using wifi
  template: src=interfaces-master.j2 dest=/media/root/etc/network/interfaces owner=root group=root
  tags: 
    - network

# -- ----------------------------------------------------------------------- --
# -- Enable forwarding and masquerading
# -- ----------------------------------------------------------------------- --
- name: be sure Ipv4 forwarding is enabled
  lineinfile: dest=/media/root/etc/sysctl.conf regexp='^net.ipv4.ip_forward=' line='net.ipv4.ip_forward=1'
  tags:
    - network
    - nat

- name: be sure the correct iptables configuration is read
  copy: src=iptables.j2 dest=/media/root/etc/iptables.sav
  tags:
    - network
    - nat

- name: be sure the iptables configuration are read at the end of the runlevel 
  copy: src=rc.local dest=/media/root/etc/rc.local
  tags:
    - network
    - nat